import type { Metadata } from "next";
import { ScrollToTop } from "@/components/ScrollToTop";
import { NavBar } from "@/components/NavBar";
import { SiteFooter } from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Terms of Service — WebsiteCreditScore",
  description: "Terms of service for WebsiteCreditScore.com — pay-per-scan website intelligence.",
};

export default function TermsPage() {
  return (
    <main className="flex min-h-screen flex-col" style={{ backgroundColor: "var(--theme-background)" }}>
      <ScrollToTop />
      <NavBar />

      <article className="max-w-2xl mx-auto px-6 py-16 space-y-10 flex-1 w-full">
        <div className="space-y-2">
          <h1 className="font-display" style={{ fontSize: "clamp(2rem,4vw,2.8rem)", color: "var(--theme-foreground)" }}>
            Terms of Service
          </h1>
          <p className="text-sm" style={{ color: "var(--theme-muted)" }}>Last updated: April 26, 2026</p>
        </div>

        <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
          These Terms govern your use of WebsiteCreditScore.com (the &ldquo;Service&rdquo;). By purchasing a scan or using the Service, you agree to these Terms. If you don&rsquo;t agree, don&rsquo;t use the Service.
        </p>

        {[
          {
            title: "1. The Service",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                WebsiteCreditScore.com provides AI-powered website auditing and scoring. We run live web searches against publicly accessible information about a domain and generate a scored report across ten dimensions. Reports are informational only — not financial, legal, or investment advice.
              </p>
            ),
          },
          {
            title: "2. No account required",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                The Service is available without registration. You purchase scans on a pay-per-scan basis. Bundle credits are tied to your order and accessed via your purchase confirmation.
              </p>
            ),
          },
          {
            title: "3. Payment and credits",
            content: (
              <div className="space-y-3 text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                <p>Payments are processed by Stripe. By completing checkout, you authorize us to charge the amount shown for your selected scan tier.</p>
                <p>Each scan consumes one credit at the purchased tier. Credits are non-refundable once consumed. Bundle credits do not expire.</p>
                <p>
                  If the AI fails to produce a valid report for any reason (server error, timeout, parsing failure),
                  you will be automatically refunded the cost of that scan within 5 business days via Stripe. The full
                  refund policy is published at <a href="/refunds" className="underline underline-offset-2" style={{ color: "var(--theme-accent)" }}>/refunds</a>.
                </p>
              </div>
            ),
          },
          {
            title: "4. Acceptable use",
            content: (
              <div className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                <p className="mb-2">You agree not to:</p>
                <ul className="space-y-1.5 list-disc list-inside">
                  <li>Use the Service to harass, defame, or harm individuals or organizations.</li>
                  <li>Attempt to reverse-engineer the scoring rubric or AI prompts for commercial resale.</li>
                  <li>Resell scan reports as your own original research without attribution.</li>
                  <li>Use automated tools to submit bulk scan requests in a way that degrades service for others.</li>
                  <li>Use the Service in violation of any applicable law.</li>
                </ul>
              </div>
            ),
          },
          {
            title: "5. AI output disclaimer",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                Reports are generated by large language models using live web search results. AI-generated content may contain inaccuracies, outdated information, or errors. You are responsible for reviewing any report before making decisions based on it. We make no warranty that scores are accurate for your specific circumstances.
              </p>
            ),
          },
          {
            title: "6. Intellectual property",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                You retain no claim over the Service, scoring engine, rubric, or AI-generated methodology. Reports we produce for you may be used for your own business purposes, including sharing with clients or colleagues. The shareable report URL is public — anyone with the link can view the report.
              </p>
            ),
          },
          {
            title: "7. Limitation of liability",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF YOUR USE OF THE SERVICE IS LIMITED TO THE AMOUNT YOU PAID FOR THE SPECIFIC SCAN(S) GIVING RISE TO THE CLAIM. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES.
              </p>
            ),
          },
          {
            title: "8. Warranty disclaimer",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND. WE DO NOT WARRANT UNINTERRUPTED ACCESS, ERROR-FREE OPERATION, OR FITNESS FOR ANY PARTICULAR PURPOSE.
              </p>
            ),
          },
          {
            title: "9. Termination",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                We may suspend or terminate access to the Service for violations of these Terms. Unused bundle credits are forfeited upon termination for cause. We reserve the right to discontinue the Service with reasonable notice.
              </p>
            ),
          },
          {
            title: "10. Governing law",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                These Terms are governed by the laws of the State of Delaware, without regard to conflicts-of-laws principles.
              </p>
            ),
          },
          {
            title: "11. Changes",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                We may update these Terms at any time. Material changes will be noted here with a new date. Continued use after changes means you accept the updated Terms.
              </p>
            ),
          },
          {
            title: "12. Contact",
            content: (
              <p className="text-sm leading-relaxed" style={{ color: "var(--theme-muted)" }}>
                Questions:{" "}
                <a href="mailto:hello@websitecreditscore.com" className="underline underline-offset-2 hover:opacity-80" style={{ color: "var(--theme-accent)" }}>
                  hello@websitecreditscore.com
                </a>
              </p>
            ),
          },
        ].map(({ title, content }) => (
          <section key={title} className="space-y-3">
            <h2 className="text-base font-semibold" style={{ color: "var(--theme-foreground)" }}>{title}</h2>
            <div style={{ borderTop: "1px solid var(--theme-border)" }} className="pt-3">
              {content}
            </div>
          </section>
        ))}
      </article>

      <SiteFooter />
    </main>
  );
}
