import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Award,
  BarChart3,
  Bot,
  Building2,
  Clock,
  Eye,
  FileText,
  Gauge,
  Handshake,
  HeartHandshake,
  Hourglass,
  LifeBuoy,
  MapPin,
  MousePointer2,
  Palette,
  Presentation,
  Search,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Star,
  Timer,
  TrendingUp,
  Zap,
} from "lucide-react";

const BLOG_SLUG_ICONS: Record<string, LucideIcon> = {
  "the-90-second-website-audit": Hourglass,
  "what-your-competitors-website-scores-tell-you": BarChart3,
  "vendor-vetting-with-website-scans": Handshake,
  "local-service-business-website-credibility": MapPin,
  "nonprofit-website-credibility-donor-trust": HeartHandshake,
  "how-to-respond-to-a-bad-website-credit-score": LifeBuoy,
  "anatomy-of-a-scam-website": ShieldAlert,
  "eeat-signals-for-small-business-websites": Award,
  "how-ai-agents-evaluate-your-website": Bot,
  "website-credibility-check-before-you-buy": ShoppingCart,
  "how-to-check-if-a-website-is-legit": ShieldCheck,
  "website-trust-scores-explained": Gauge,
  "why-your-website-looks-untrustworthy": AlertTriangle,
  "online-reputation-audit": Search,
  "red-flags-customers-notice-in-5-seconds": Timer,
  "from-credibility-score-to-sales-pitch": Presentation,
  "business-legitimacy": Building2,
  "online-reputation": Star,
  "visual-design": Palette,
  "ux-conversion": MousePointer2,
  transparency: Eye,
  "technical-health": Zap,
  "content-quality": FileText,
  "social-presence": Share2,
  longevity: Clock,
  "financial-signals": TrendingUp,
};

export function getBlogIconForSlug(slug: string): LucideIcon {
  return BLOG_SLUG_ICONS[slug] ?? FileText;
}
